### ISSUE TITLE
ADD  QUESTIONS

### ISSUE THREAD

**Issue by Sopha-Rath** [Sopha-Rath/2022-QUIZZ-APP-G10#1]
Add question to element

TO DO:

- create a form(could I create a form by HTML or using js?
- question, possible answers
- select the correct answer
- function to append new questions in data

**Comment by harrahx3** [comment]
Pretty good !
Good to get the list of answers and the good one, and the user can also edit the questions !
But I think you have a problem to get the question itself: 
`let add_questions = document.querySelectorAll("#question");`
Because you have only one element with id "question"

**Comment by VANSAOHANG** [comment]
want to add questions and answers in the same object
